INSERT INTO USER VALUES (1, 'Pedro', 1);
INSERT INTO USER VALUES (2, 'Paulo', 2);
INSERT INTO USER VALUES (3, 'Luis', null);

INSERT INTO USER_DETAILS VALUES (1, 1, 'portuguese');
INSERT INTO USER_DETAILS VALUES (2, 2, 'portuguese');
INSERT INTO USER_DETAILS VALUES (3, 3, 'portuguese');

INSERT INTO CONTACT_DETAILS VALUES (1, '+351229999999', 'email@pedro.com');
INSERT INTO CONTACT_DETAILS VALUES (2, '+351229999999', 'email@paulo.com');